const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({ executablePath: '/opt/playwright-browsers/chromium-1209/chrome-linux64/chrome', args: ['--no-sandbox'] });
  const p = await (await b.newContext({ viewport: { width: 390, height: 844 } })).newPage(); const pe = []; p.on('pageerror', e => pe.push(String(e).slice(0, 160)));
  const U = x => 'https://cq78ba4p.qwenwork.page/?SM' + x + Date.now();
  await p.goto(U('0') + '#/', { waitUntil: 'networkidle' }); await p.waitForTimeout(600);
  await p.evaluate(() => { const r = Store.signup('Smoke Elek', 'smoke@v52.io', 'smokepassx1', 'Gyergyó'); if (r.ok) { Store.me().onboarded = true; Store.save(); } return r.ok; });
  await p.goto(U('1') + '#/szervezo', { waitUntil: 'networkidle' }); await p.waitForTimeout(1300);
  console.log('K0 üres központ:', await p.evaluate(() => /Szervezői központ/.test(document.body.innerText) && /Szervezőként csatlakozom/.test(document.body.innerText)));
  await p.evaluate(() => { const x = document.getElementById('e2-reg'); x && x.click(); }); await p.waitForTimeout(600);
  await p.evaluate(() => { const m = document.querySelector('[data-modal]'); m.querySelector('#e2o_reg').value = 'Gyergyó'; m.querySelector('#e2o_save').click(); }); await p.waitForTimeout(900);
  console.log('K1 org kész:', await p.evaluate(() => { const o=Store.platform().organizers.find(x=>x.owner===String(Store.me().email)); return !!o; }));
  await p.evaluate(() => { const x = document.getElementById('e2-new'); x && x.click(); }); await p.waitForTimeout(700);
  await p.evaluate(() => { const m = document.querySelector('[data-modal]'); const g = (id, v) => { const e = m.querySelector(id); if (e) e.value = v; };
    g('#e2f_name', 'SMOKE Turistátúra 2026'); g('#e2f_date', '2026-11-28'); g('#e2f_time', '09:00'); g('#e2f_place', 'Csíki-havasok'); g('#e2f_region', 'Csík'); g('#e2f_km', '13'); g('#e2f_up', '700'); g('#e2f_h', '5'); g('#e2f_cap', '20'); g('#e2f_desc', 'Smoke leírás');
    m.querySelector('#e2f_save').click(); }); await p.waitForTimeout(900);
  const e2 = await p.evaluate(() => { const e = (Store.platform().events || []).find(x => /SMOKE/.test(x.name)); return e ? { id: e.id, st: e.status } : null; });
  console.log('K2 létrehozva:', JSON.stringify(e2));
  await p.evaluate(id => { const x = document.querySelector('[data-e2st="' + id + ':published"]'); x && x.click(); }, (e2 || {}).id); await p.waitForTimeout(800);
  console.log('K3 publikálva:', await p.evaluate(id => { const e = Store.platform().events.find(x => x.id === id); return e && e.status === 'published'; }, (e2 || {}).id));
  await p.goto(U('2') + '#/felfedezes', { waitUntil: 'networkidle' }); await p.waitForTimeout(1200);
  await p.evaluate(() => { const t = document.querySelector('[data-f9tab="events"]'); t && t.click(); }); await p.waitForTimeout(800);
  await p.evaluate(() => { document.querySelectorAll('#f9-list details').forEach(d => { d.open = true; }); }); await p.waitForTimeout(450);
  console.log('K4 felfedezésben él:', await p.evaluate(() => [...document.querySelectorAll('#f9-list .f9card')].some(c => /SMOKE Turistátúra/.test(c.innerText))));
  await p.evaluate(() => { const c = [...document.querySelectorAll('#f9-list .f9card')].find(x => /SMOKE/.test(x.innerText)); const bb = c && c.querySelector('[data-f9ev]'); bb && bb.click(); }); await p.waitForTimeout(800);
  console.log('K5 modal extrák:', await p.evaluate(() => { const m = document.querySelector('[data-modal]'); return !!m && /Jelentkezem/.test(m.innerText) && !!m.querySelector('[data-e2join]'); }));
  await p.evaluate(() => { const m = document.querySelector('[data-modal]'); const x = m.querySelector('[data-e2cal]'); x && x.click(); }); await p.waitForTimeout(700);
  console.log('K6 naptár:', await p.evaluate(() => (Store.myData().savedEvents || []).some(x => x.indexOf('p2-') === 0)));
  await p.evaluate(() => { const m = document.querySelector('[data-modal]'); const x = m.querySelector('[data-e2join]'); if (x) x.click(); }); await p.waitForTimeout(800);
  console.log('K7 regisztr state:', await p.evaluate(() => JSON.stringify((Store.platform().participants || []).map(y => y.status))));
  await p.goto(U('3') + '#/szervezo', { waitUntil: 'networkidle' }); await p.waitForTimeout(1100);
  await p.evaluate(() => { const x = document.querySelector('[data-e2app]'); x && x.click(); }); await p.waitForTimeout(700);
  console.log('K8 lista:', await p.evaluate(() => { const m = document.querySelector('[data-modal]'); return !!m && (/Smoke Elek|Túrázó/.test(m.innerText)) && /Elküldve/.test(m.innerText); }));
  await p.evaluate(() => { const x = document.querySelector('[data-e2dec]'); x && x.click(); }); await p.waitForTimeout(800);
  console.log('K9 elfogadva:', await p.evaluate(() => (Store.platform().participants[0] || {}).status));
  console.log('PE:', pe.slice(0, 4));
  await b.close();
})().catch(e => console.log('H', e.message.slice(0, 200)));
