/* V43 E2E (24) + V42 regressziok — eloe: cd <work>/tests && NODE_PATH=/usr/lib/node_modules node v43e2e.js */
const { chromium } = require('playwright');
const R=[]; const ok=(n,c,d='')=>{R.push({n:n,c:!!c,d:d}); console.log((c?'✓ ':'✗ ')+n+(d?' — '+d:''));};
(async()=>{ const b=await chromium.launch({executablePath:'/opt/playwright-browsers/chromium-1209/chrome-linux64/chrome',args:['--no-sandbox']});
 const p=await b.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,170)));
 const U=n=>"https://cq78ba4p.qwenwork.page/?E43F_"+n+"_"+Math.random();
 const db=(f,a)=>p.evaluate(f,a);
 // 1: uj user
 await p.goto(U(0)+"#/",{waitUntil:'networkidle'}); await p.waitForTimeout(700);
 const setup=await db(()=>{ Store.signup('Planlek Elek','pl'+Math.random().toString(36).slice(2)+'@e43.hu','planlekpass1','Gyergyó');
   Store.me().onboarded=true; Store.save();
   const d=Store.myData(); d.equipment.push({id:"eqX",name:"Fejlámpa",cat:"Electronika",has:true,w:110,cond:"Jó"});
   const t=Store.newTourFromDraft({title:"Hargita napkelte E2E",date:Store.addDays(Store.todayISO(),6),place:"Gyergyó",region:"gyergyó"});
   t.timeline=[]; t.food=[{id:"f0",n:"Víz 1 l",i:"💧",checked:false,w:1000}]; t.gear=[]; t.tasks=[]; Store.save();
   return {ok:true,id:t.id}; });
 ok("1 új túra létrehozva", setup.ok);
 const tid=setup.id;
 await p.goto(U(1)+"#/tura/"+tid,{waitUntil:'networkidle'}); await p.waitForTimeout(1200);
 await db(i=>{ const x=Store.myData().tours.find(y=>y.id===i); x.date=Store.addDays(Store.todayISO(),6); x.place="Gyergyó"; x.lengthKm=13; x.ascent=780; x.durationH=5; x.difficulty="Nehéz"; Store.save(); return true;}, tid);
 const ok24=await db(i=>{const x=Store.myData().tours.find(y=>y.id===i);return !!(x.date&&x.place&&x.lengthKm===13&&x.ascent===780);},tid);
 ok("2-5 dátum, hely, táv, szint, saját cucc a tárban", ok24 && await db(()=>Store.myData().equipment.some(e=>e.name==="Fejlámpa"&&e.has)));
 await p.goto(U(2)+"#/tura/"+tid,{waitUntil:'networkidle'}); await p.waitForTimeout(1100);
 ok("6 gomb: 🤖 Tervezd meg ezt a túrát", await db(()=>{const el=document.getElementById('btn-ai'); return el&&/Tervezd meg/.test(el.textContent);}));
 await db(()=>document.getElementById('btn-ai').click()); await p.waitForTimeout(300);
 ok("7 statcléptetés (Túra adatai → …)", await db(()=>!!document.querySelector('.sp-step')));
 await p.waitForTimeout(1400);
 ok("8 modal: Okos túratervező", await db(()=>/Okos túratervez/.test(document.body.innerText)));
 ok("9 idővonal szerkeszthető", await db(()=>!!document.querySelector('#sp-time input[type="time"]')&&!!document.querySelector('#sp-time .sp-l')));
 await db(()=>{const r0=document.querySelector('#sp-time .sp-row'); r0.querySelector('.sp-l').value="Indulás a szállás eléől";});
 const pak=await db(()=>{ return {own:document.querySelectorAll('[data-gadd][data-own="1"]').length, need:document.querySelectorAll('[data-gadd]:not([data-own])').length}; });
 ok("10 pakolás: saját és szükséges külön", pak.own>=1, JSON.stringify(pak));
 await db(()=>{const el=document.querySelector('[data-gadd][data-own="1"]'); el&&el.click();});
 ok("10b '+ Saját tárból' azonnal belerak", await db(i=>{const x=Store.myData().tours.find(y=>y.id===i); return x.gear.some(g=>g.own);}, tid));
 ok("10c fejlámpa bekerült (own)", await db(i=>{const x=Store.myData().tours.find(y=>y.id===i); return x.gear.some(g=>/Fejl/.test(g.name));}, tid));
 ok("11 étel/víz szekció", await db(()=>!!document.querySelector('[data-fadd]')));
 ok("12 feladat-lista (javasolt 5)", await db(()=>document.querySelectorAll('[data-tadd]').length>=4));
 // kategóriák: idővonal KI, tobbi BE
 await db(()=>{ const set=(k,v)=>{const el=document.querySelector(`[data-cat="${k}"]`); if(el&&!el.disabled) el.checked=v;};
   set("idoter",false); set("pakolas",true); set("etel",true); set("task",true); });
 const before=await db(i=>{const x=Store.myData().tours.find(y=>y.id===i);return {g:x.gear.length,f:x.food.length,t:x.tasks.length,tl:x.timeline.length};},tid);
 await db(()=>{const el=document.getElementById('sp-apply'); el&&el.click();}); await p.waitForTimeout(1100);
 const after=await db(i=>{const x=Store.myData().tours.find(y=>y.id===i); return {g:x.gear.length,f:x.food.length,t:x.tasks.length,tl:x.timeline.length,pct:Store.readiness(x).pct};},tid);
 ok("13-16 alkalmazva, readiness nőtt(valós)", after.pct>20 && after.t>=5 && after.g>=before.g && after.f>=before.f, JSON.stringify({before:before,after:after}));
 // 17 duplikacio
 await p.goto(U(3)+"#/tura/"+tid,{waitUntil:'networkidle'}); await p.waitForTimeout(1000);
 await db(()=>{const b=document.getElementById('btn-ai');b&&b.click();}); await p.waitForTimeout(1600);
 const gB=await db(i=>Store.myData().tours.find(y=>y.id===i).gear.length,tid);
 await db(()=>{const el=document.getElementById('sp-apply');el&&el.click();}); await p.waitForTimeout(900);
 const gA=await db(i=>Store.myData().tours.find(y=>y.id===i).gear.length,tid);
 ok("17 ismételt alkalmazás: nincs dupli gear", gA===gB, gB+"→"+gA);
 // 18 dashboard
 await p.goto(U(4)+"#/vezerlopult",{waitUntil:'networkidle'}); await p.waitForTimeout(2000);
 const mx=await db(()=>Math.max.apply(null,[...document.querySelectorAll('#widgets [data-w]')].map(x=>Math.round(x.getBoundingClientRect().height))));
 ok("18 dashboard: max widget magasság", mx>0 && mx<=560, "max="+mx);
 await p.goto(U(5)+"#/naptar",{waitUntil:'networkidle'}); await p.waitForTimeout(900);
 ok("19 naptár jelöli", await db(()=>!!document.querySelector('.cal-pill.cp-plan')));
 await p.goto(U(6)+"#/tura/"+tid,{waitUntil:'networkidle'}); await p.waitForTimeout(900);
 await db(()=>{const b=document.querySelector('[data-wstab="felszereles"]');b&&b.click();}); await p.waitForTimeout(800);
 ok("20 Packing: fejlámpa+ súlyjelleg", await db(()=>/Fejl/.test(document.getElementById('view').innerText)&&/kg|hátizs|összes/i.test(document.getElementById('view').innerText)));
 await db(()=>{const b=document.querySelector('[data-wstab="teendok"]');b&&b.click();}); await p.waitForTimeout(800);
 ok("21 Tasks: javasolt feladatok bent", await db(()=>/Időjár|Víz|Társ|Aut|felszerel/i.test(document.getElementById('view').innerText)));
 await db(()=>{const b=document.querySelector('[data-wstab="ete"]');b&&b.click();}); await p.waitForTimeout(800);
 ok("22 Étel: víztétel bent", await db(()=>/Víz/.test(document.getElementById('view').innerText)));
 await db(()=>{const b=document.querySelector('[data-wstab="utazas"]');b&&b.click();}); await p.waitForTimeout(800);
 ok("23 Transport: kitalált sofőr nélkül él", await db(()=>/Autók|szabad hely|Indulási/.test(document.getElementById('view').innerText)));
 await db(()=>{const b=document.querySelector('[data-wstab="koltseg"]');b&&b.click();}); await p.waitForTimeout(800);
 ok("24 Costs él", await db(()=>/Költség|össz|€.*/i.test(document.getElementById('view').innerText)));
 console.log("\n== V42 regressziok ==");
 await p.goto(U(7)+"#/tura/"+tid,{waitUntil:'networkidle'}); await p.waitForTimeout(800);
 ok("R időjárás-gomb + btn", await db(()=>!!document.getElementById('btn-wx')));
 await db(()=>{const b=document.getElementById('btn-wx');b&&b.click();}); await p.waitForTimeout(3300);
 ok("R readiness-szöveg", await db(()=>/Még \d+ dolog van hátra|Indulásra kész/.test(document.getElementById('view').innerText)));
 // teljesítés-élmény röviden
 const t2=await db(i=>{ const x=Store.myData().tours.find(y=>y.id===i); x.date=Store.addDays(Store.todayISO(),-1); Store.save(); return true;}, tid);
 await p.goto(U(8)+"#/turaim",{waitUntil:'networkidle'}); await p.waitForTimeout(900);
 ok("R Teljesítettem gomb elERHETŐ", await db(()=>!!document.querySelector('[data-complete]')));
 await db(()=>{const b=document.querySelector('[data-complete]');b&&b.click();}); await p.waitForTimeout(500);
 await db(()=>{const g=document.getElementById('do-complete');g&&g.click();}); await p.waitForTimeout(800);
 ok("R 🎉 gratulómodal", await db(()=>!!document.getElementById('cg-now')));
 await db(()=>{const n=document.getElementById('cg-now');n&&n.click();}); await p.waitForTimeout(500);
 await db(()=>{const s=document.getElementById('mm-story'); s.value="Hajnali fény a tetején."; const v=document.getElementById('mm-save');v&&v.click();}); await p.waitForTimeout(1200);
 ok("R élmény elmentve + nem duplikál", await db(()=>{const d=Store.myData(); const js=d.journal.filter(j=>/HARGITA|Hargita/.test(j.title)); return js.length===1 && /Hajnali/.test(js[0].note);}), await db(()=>{const d=Store.myData(); return d.journal.length+" journal, km="+Store.stats().yearKm.toFixed(0);}));
 // inbox
 await p.goto(U(9)+"#/inbox",{waitUntil:'networkidle'}); await p.waitForTimeout(800);
 await db(()=>{const nb=document.getElementById('ib26-new'); nb&&nb.click();}); await p.waitForTimeout(500);
 await db(()=>{const nt=document.querySelector('[data-bt="note"]'); nt&&nt.click();}); await p.waitForTimeout(300);
 await db(()=>{const ti=document.getElementById('ib26f_note'); if(ti){ti.value='Inbox teszt 2026.12.24';} const sv=document.getElementById('ib26-save'); sv&&sv.click();}); await p.waitForTimeout(700);
 ok("R Inbox → terv gomb él a kártyán", await db(()=>!!document.querySelector('.ib26-card [data-ib2t],[data-ib-plan]')));
 console.log("\nSUMMARY: "+R.filter(x=>x.c).length+"/"+R.length+" | pageerrors: "+errs.length);
 if(errs.length) console.log(errs);
 await b.close(); })();
