/* ============================================================
   V127 — valódi ORS/HeiGIT útvonaltervező
   A frontend csak a Supabase Edge Function route-proxy-t hívja. Az ORS-kulcs
   soha nem kerül a bundle-be; a mentés a meglévő d.routes + routeId rendszert használja.
   ============================================================ */
(function(){
"use strict";
var cache=new Map(), inflight=new Map(), plannerMap=null, mapLayers=[], current=null;
var ORS_SOURCE="https://api.heigit.org/openrouteservice/v2/";
function api(){ return window.__V54&&window.__V54.api&&typeof window.__V54.api.routingPlan==="function"?window.__V54.api:null; }
function esc127(v){ return typeof esc==="function"?esc(v==null?"":String(v)):String(v==null?"":v).replace(/[&<>\"']/g,function(c){return ({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"})[c];}); }
function msg127(e){ var c=e&&(e.error||e.code)||""; return ({routing_not_configured:"Az útvonaltervező szerveroldali kulcsa még nincs beállítva.",routing_rate_limited:"Túl sok kérés érkezett. Próbáld újra később.",routing_provider_unavailable:"Az útvonaltervező szolgáltató most nem érhető el.",routing_invalid_request:"A szolgáltató nem tudott útvonalat számítani ezekkel a pontokkal.",invalid_points:"Adj meg érvényes kezdő- és végpontot.",same_points:"A kezdő- és végpont nem lehet azonos.",invalid_profile:"Válassz gyalogos vagy terepi profilt.",network:"Az új útvonal tervezéséhez internetkapcsolat szükséges."}[c]||((e&&e.message)||"Az útvonaltervezés most nem sikerült.")); }
function parsePoint(value){ var m=String(value||"").trim().replace(/;/g,",").match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/); if(!m)return null; var lat=+m[1],lng=+m[2]; return lat>=-90&&lat<=90&&lng>=-180&&lng<=180?{lat:lat,lng:lng,label:lat.toFixed(5)+", "+lng.toFixed(5)}:null; }
function inputPoint(root,id){ var el=root.querySelector(id); if(!el)return null; var p=el.__v127Point||parsePoint(el.value); if(!p)return null; return {lat:+p.lat,lng:+p.lng,label:p.label||el.value}; }
function setInputPoint(root,id,p){ var el=root.querySelector(id); if(!el||!p)return; el.__v127Point={lat:+p.lat,lng:+p.lng,label:p.label||""}; el.value=p.label||(+p.lat).toFixed(5)+", "+(+p.lng).toFixed(5); el.dataset.lat=String(p.lat); el.dataset.lng=String(p.lng); }
function clearPoint(el){ if(el){ delete el.__v127Point; delete el.dataset.lat; delete el.dataset.lng; } }
function providerKey(start,end,profile){ return [profile,start.lat.toFixed(5),start.lng.toFixed(5),end.lat.toFixed(5),end.lng.toFixed(5)].join("|"); }
function geometryToTrack(coords){ return (Array.isArray(coords)?coords:[]).map(function(p){ if(!Array.isArray(p)||p.length<2)return null; var lng=+p[0],lat=+p[1],ele=p.length>2&&Number.isFinite(+p[2])?+p[2]:null; return Number.isFinite(lat)&&Number.isFinite(lng)?[lat,lng,ele,null]:null; }).filter(Boolean); }
function routesFromResponse(data,profile,start,end){
  var fs=data&&Array.isArray(data.features)?data.features:[];
  return fs.map(function(f,i){ var prop=f&&f.properties||{}, sum=prop.summary||{}, track=geometryToTrack(f&&f.geometry&&f.geometry.coordinates); if(track.length<2)return null; return {index:i,profile:profile,track:track,distanceM:Number.isFinite(+sum.distance)?+sum.distance:null,durationS:Number.isFinite(+sum.duration)?+sum.duration:null,ascent:Number.isFinite(+sum.ascent)?+sum.ascent:null,descent:Number.isFinite(+sum.descent)?+sum.descent:null,start:start,end:end,feature:f}; }).filter(Boolean);
}
function routeRequest(start,end,profile){ var key=providerKey(start,end,profile); if(cache.has(key))return Promise.resolve(cache.get(key)); if(inflight.has(key))return inflight.get(key); var A=api(); if(!A)return Promise.reject({error:"routing_not_configured"}); var p=A.routingPlan({start:{lat:start.lat,lng:start.lng},end:{lat:end.lat,lng:end.lng},profile:profile,alternatives:true}).then(function(data){ var routes=routesFromResponse(data,profile,start,end); if(!routes.length)throw {error:"routing_invalid_request",message:"A szolgáltató nem adott vissza használható útvonal-geometriát."}; routes.forEach(function(route){route.name=(start.label||"Kezdőpont")+" – "+(end.label||"Célpont");}); var out={routes:routes,source:ORS_SOURCE}; cache.set(key,out); return out; }).finally(function(){inflight.delete(key);}); inflight.set(key,p); return p; }
function fKm(m){ return m==null?"nincs adat":(Math.round(m/100)/10).toFixed(1).replace(".",",")+" km"; }
function fTime(s){ if(s==null)return "nincs adat"; var min=Math.round(s/60),h=Math.floor(min/60),m=min%60; return h?(h+" ó"+(m?" "+m+" p":"")):(m+" p"); }
function fM(m){ return m==null?"nincs adat":"+"+Math.round(m)+" m"; }
function xml(v){ return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;"); }
function gpx(route){ var pts=route.track||[], body=pts.map(function(p){return '    <trkpt lat="'+p[0]+'" lon="'+p[1]+'">'+(p[2]!=null?'<ele>'+p[2]+'</ele>':"")+"</trkpt>";}).join("\n"); return '<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="Túratárs · OpenRouteService" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>'+xml(route.name||"ORS útvonal")+'</name><link href="'+ORS_SOURCE+'"/></metadata><trk><name>'+xml(route.name||"ORS útvonal")+'</name><trkseg>\n'+body+'\n</trkseg></trk></gpx>\n'; }
function download(route){ var a=document.createElement("a"),url=URL.createObjectURL(new Blob([gpx(route)],{type:"application/gpx+xml"})); a.href=url;a.download=(route.name||"ors-utvonal").replace(/[^\w-]+/g,"_").slice(0,60)+".gpx";document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(url);a.remove();},800);toast("A tényleges ORS-geometriából készült GPX letöltve.","📤"); }
function fp(route){ var a=route.track[0],b=route.track[route.track.length-1]; return ["openrouteservice",route.profile,route.track.length,a[0].toFixed(5),a[1].toFixed(5),b[0].toFixed(5),b[1].toFixed(5),Math.round((route.distanceM||0)/10)].join("|"); }
function saveRoute(route){ if(!Store.me()){toast("Mentéshez jelentkezz be.","🔐");NAV.to("#/belepes");return null;} var d=Store.myData(), f=fp(route), old=(d.routes||[]).find(function(r){return r&&((r.fp===f)||(r.__fp===f));}); if(old)return old; var p=route.track[0],q=route.track[route.track.length-1]; var r={id:Store.uid("rt"),name:route.name||"Útvonaltervező útvonal",source:"openrouteservice",source_url:ORS_SOURCE,sourceLicense:"OpenStreetMap ODbL 1.0; OpenRouteService",attribution:"© OpenStreetMap contributors · OpenRouteService",provenance:{provider:"openrouteservice",endpoint:ORS_SOURCE,profile:route.profile,calculatedAt:new Date().toISOString()},fp:f,__fp:f,distance_km:route.distanceM==null?null:Math.round(route.distanceM/100)/10,elevation_gain_m:route.ascent,elevation_loss_m:route.descent,duration_s:route.durationS,start:{lat:p[0],lng:p[1]},finish:{lat:q[0],lng:q[1]},track:route.track,nPts:route.track.length,raw:null,created_at:new Date().toISOString()}; d.routes=d.routes||[];d.routes.unshift(r);Store.save();return r; }
function cloudSnapshot(){ try{ var v=window.__V54&&window.__V54.st&&window.__V54.st(); if(!v||!v.token||v.remoteVersion==null||!window.__V54.api.save)return Promise.resolve(null); return window.__V54.api.save(window.__V54.build(v.email)); }catch(e){return Promise.reject(e);} }
function createTour(route){ if(!Store.me()){toast("Túra készítéséhez jelentkezz be.","🔐");NAV.to("#/belepes");return null;} var r=saveRoute(route); if(!r)return null; var t=Store.newTourFromDraft({title:route.name||"Tervezett útvonal",place:route.start.label||"",region:"",date:"",status:"tervezés",lengthKm:r.distance_km,ascent:r.elevation_gain_m,durationH:r.durationS==null?0:Math.round(route.durationS/360)/10,difficulty:route.profile==="foot-hiking"?"Terepi túra":"Gyalogos",coords:r.start,desc:"Útvonaltervező által számított útvonal · "+fKm(route.distanceM),notes:"Forrás: OpenRouteService / OpenStreetMap · "+ORS_SOURCE,tags:["openrouteservice"]}); t.routeId=r.id;r.linkedRouteSource="openrouteservice";Store.save();r.linkedTripId=t.id;Store.save();return t; }
function startGps(route){ var t=createTour(route);if(!t)return; if(typeof window.v120Begin==="function")window.v120Begin(t.id);else NAV.to("#/tura/"+t.id); }
function clearMap(){ mapLayers.forEach(function(x){try{x.remove();}catch(e){}});mapLayers=[]; }
function drawMap(root,routes,selected){ var el=root.querySelector("#v127-map");if(!el||typeof MapKit==="undefined"||!window.L)return;clearMap();if(plannerMap){try{plannerMap.remove();}catch(e){}plannerMap=null;}var r=routes[selected];if(!r||!r.track.length)return;plannerMap=MapKit.make(el,{center:[r.track[0][0],r.track[0][1]],zoom:11,scroll:true});if(!plannerMap)return;routes.forEach(function(x,i){var line=x.track.map(function(p){return [p[0],p[1]];});var l=L.polyline(line,{color:i===selected?"#E07A2F":"#2F6B4A",weight:i===selected?5:3,opacity:i===selected?0.95:0.35}).addTo(plannerMap);mapLayers.push(l);});var pts=r.track.map(function(p){return [p[0],p[1]];});var s=L.circleMarker(pts[0],{radius:7,color:"#1C4A36",fillColor:"#2F6B4A",fillOpacity:1}).addTo(plannerMap),e=L.circleMarker(pts[pts.length-1],{radius:7,color:"#8C3B24",fillColor:"#E07A2F",fillOpacity:1}).addTo(plannerMap);mapLayers.push(s,e);plannerMap.fitBounds(L.latLngBounds(pts).pad(.15)); }
function resultHtml(routes,selected){ var r=routes[selected], alts=routes.length>1?'<div class="v127-alts"><b>Valódi alternatívák</b>'+routes.map(function(x,i){return '<button class="btn btn-ghost btn-sm '+(i===selected?'on':'')+'" data-v127-alt="'+i+'">'+(i===selected?'✓ ':'')+(i===0?'Ajánlott ':'Alternatíva ')+(i+1)+' · '+fKm(x.distanceM)+' · '+fTime(x.durationS)+'</button>';}).join("")+'</div>':""; return '<section class="card panel v127-result"><div class="sect-head"><div><span class="eyebrow">Valódi szolgáltatói eredmény</span><h2 class="mb0">🗺️ Számított útvonal</h2></div><span class="chip chip-green">OpenRouteService</span></div><div class="v127-stats"><span><b>'+fKm(r.distanceM)+'</b><small>Táv</small></span><span><b>'+fTime(r.durationS)+'</b><small>Becsült idő</small></span><span><b>'+fM(r.ascent)+'</b><small>Szint</small></span><span><b>'+esc127(r.profile==="foot-hiking"?"Terepi/túra":"Gyalog")+'</b><small>Profil</small></span></div><div id="v127-map" class="mapbox v127-map"><div class="empty">A tényleges útvonal-geometria betöltése…</div></div><p class="small muted">Kezdés: '+esc127(r.start.label||((+r.start.lat).toFixed(5)+", "+(+r.start.lng).toFixed(5)))+' · Cél: '+esc127(r.end.label||((+r.end.lat).toFixed(5)+", "+(+r.end.lng).toFixed(5)))+' · Forrás: OpenRouteService / OpenStreetMap</p>'+alts+'<div class="v127-actions"><button class="btn btn-soft" data-v127-export>📤 GPX export</button><button class="btn btn-primary" data-v127-save>💾 Mentés útvonalként</button><button class="btn btn-ember" data-v127-tour>🗓️ Túra készítése</button><button class="btn btn-ghost" data-v127-start>🥾 Indulok</button></div></section>'; }
function showResults(root,out){ var host=root.querySelector("#v127-result");if(!host)return;host.innerHTML=resultHtml(out.routes,out.selected||0);var selected=out.selected||0;drawMap(root,out.routes,selected);host.querySelectorAll("[data-v127-alt]").forEach(function(b){b.onclick=function(){out.selected=+b.dataset.v127Alt;showResults(root,out);};});host.querySelector("[data-v127-export]").onclick=function(){download(out.routes[selected]);};host.querySelector("[data-v127-save]").onclick=function(){var r=saveRoute(out.routes[selected]);if(!r)return;cloudSnapshot().then(function(){toast("Útvonal mentve a saját útvonalaid közé.","💾");}).catch(function(e){toast("Helyben mentve; a cloud mentés nem sikerült: "+msg127(e),"📱");});};host.querySelector("[data-v127-tour]").onclick=function(){var t=createTour(out.routes[selected]);if(t){cloudSnapshot().then(function(){toast("Túra létrehozva a meglévő túramunkaterületen.","🗓️");NAV.to("#/tura/"+t.id);}).catch(function(e){toast("Helyben létrehozva; cloud mentés: "+msg127(e),"📱");NAV.to("#/tura/"+t.id);});}};host.querySelector("[data-v127-start]").onclick=function(){startGps(out.routes[selected]);}; }
function search(root,target){ var el=root.querySelector(target==="start"?"#v127-start":"#v127-end"), results=root.querySelector(target==="start"?"#v127-start-results":"#v127-end-results"), A=api();if(!el||!results)return;var q=String(el.value||"").trim();if(q.length<2){results.innerHTML='<p class="small muted">Írj be legalább két karaktert.</p>';return;}if(!A){results.innerHTML='<p class="small muted">'+esc127(msg127({error:"routing_not_configured"}))+'</p>';return;}results.innerHTML='<p class="small muted">Helyek keresése…</p>';A.routingSearch(q).then(function(data){var rows=Array.isArray(data&&data.results)?data.results:[];results.innerHTML=rows.length?rows.map(function(p,i){return '<button class="v127-place" data-v127-place="'+target+'" data-v127-index="'+i+'">📍 '+esc127(p.label)+'</button>';}).join(""):'<p class="small muted">Nincs találat; használhatsz lat,lng formátumot is.';results.__v127Rows=rows;}).catch(function(e){results.innerHTML='<p class="small muted">'+esc127(msg127(e))+'</p>';}); }
function gpsPoint(root,target){ if(!navigator.geolocation){toast("Ebben a böngészőben nincs GPS.","📍");return;}toast("GPS-pozíció lekérése…","📍");navigator.geolocation.getCurrentPosition(function(pos){var c=pos.coords;setInputPoint(root,target==="start"?"#v127-start":"#v127-end",{lat:c.latitude,lng:c.longitude,label:"Aktuális GPS-pozíció"});toast("A GPS-pozíció bekerült a pontba.","📍");},function(){toast("A helymeghatározási engedély szükséges.","📍");},{enableHighAccuracy:true,maximumAge:0,timeout:15000}); }
function bindMapClicks(root){ var el=root.querySelector("#v127-map-picker");if(!el||typeof MapKit==="undefined"||!window.L)return;var m=MapKit.make(el,{center:[46.4,25.7],zoom:8,scroll:true});if(!m)return;var target="start";root.querySelectorAll("[data-v127-target]").forEach(function(b){b.onclick=function(){target=b.dataset.v127Target;root.querySelectorAll("[data-v127-target]").forEach(function(x){x.classList.toggle("on",x===b);});};});m.on("click",function(e){setInputPoint(root,target,{lat:e.latlng.lat,lng:e.latlng.lng,label:"Térképen választott pont"});toast((target==="start"?"Kezdő":"Cél")+" pont kiválasztva a térképen.","📍");}); }
function run(root){ var start=inputPoint(root,"#v127-start"),end=inputPoint(root,"#v127-end"),profile=(root.querySelector("#v127-profile")||{}).value||"hiking",status=root.querySelector("#v127-status");if(!start||!end){if(status)status.textContent="Mindkét ponthoz adj meg helyet vagy koordinátát.";return;}if(status)status.textContent="Valódi útvonal kérése az OpenRouteService-től…";var begin=Date.now();routeRequest(start,end,profile).then(function(out){out.selected=0;current=out;showResults(root,out);if(status)status.textContent="Valódi útvonal érkezett a szolgáltatótól ("+(Date.now()-begin)+" ms).";}).catch(function(e){if(status)status.textContent=msg127(e);var host=root.querySelector("#v127-result");if(host)host.innerHTML="";}); }
function knownPlaceHtml(){ var rows=typeof v122PublicPlaces==="function"?v122PublicPlaces():[]; return rows.slice(0,8).filter(function(p){return p&&p.coords&&Number.isFinite(+p.coords.lat)&&Number.isFinite(+p.coords.lng);}).map(function(p){return '<button class="btn btn-ghost btn-sm v127-known-place" data-v127-known-place="'+esc127(p.id||p.name)+'" data-lat="'+(+p.coords.lat)+'" data-lng="'+(+p.coords.lng)+'" data-label="'+esc127(p.name||p.place||"Helyszín")+'">📍 '+esc127(p.name||p.place||"Helyszín")+'</button>';}).join(""); }
VIEWS.planner=function(){ var rows=typeof v125KnownRoutes==="function"?v125KnownRoutes():[];return '<div class="wrap pub-section v127-planner"><div class="sect-head"><div><span class="eyebrow">Valódi útvonaltervezés</span><h1 class="mb0">🗺️ Útvonal tervezése</h1></div></div><p class="muted">A két pont közötti útvonalat valós OpenRouteService/ OpenStreetMap adatokból számítjuk. Ha a szolgáltatás nem érhető el, nem rajzolunk helyette egyenes vagy kitalált vonalat.</p><section class="card v127-plan-card"><div class="grid g2"><label class="f">Honnan?<input class="input" id="v127-start" placeholder="Helynév vagy lat,lng"><span class="v127-search-actions"><button class="btn btn-soft btn-sm" data-v127-search="start">🔎 Hely keresése</button><button class="btn btn-ghost btn-sm" data-v127-gps="start">📍 Aktuális GPS</button></span><div id="v127-start-results" class="v127-place-results"></div></label><label class="f">Hová?<input class="input" id="v127-end" placeholder="Helynév vagy lat,lng"><span class="v127-search-actions"><button class="btn btn-soft btn-sm" data-v127-search="end">🔎 Hely keresése</button><button class="btn btn-ghost btn-sm" data-v127-gps="end">📍 Aktuális GPS</button></span><div id="v127-end-results" class="v127-place-results"></div></label></div><div class="v127-profile-row"><label class="f">Profil<select class="input" id="v127-profile"><option value="hiking">🏔️ Terepi/túra</option><option value="walking">🥾 Gyalog</option></select></label><button class="btn btn-primary btn-lg" id="v127-plan">🗺️ Útvonal tervezése</button></div><p id="v127-status" class="small muted mb0"></p></section><section class="card panel v127-picker"><div class="sect-head"><div><h2 class="mb0">Pontválasztás térképen</h2><p class="small muted mb0">Válaszd ki, melyik pontot állítod, majd kattints a térképre.</p></div><div class="v127-targets"><button class="btn btn-soft btn-sm on" data-v127-target="start">Kezdőpont</button><button class="btn btn-ghost btn-sm" data-v127-target="end">Célpont</button></div></div><div id="v127-map-picker" class="mapbox v127-map-picker"></div></section><section class="card v127-known"><h2>Ismert forrásútvonalak</h2><p class="small muted">A meglévő 37 Nagy-Hagymás GPX/KML útvonal változatlanul külön, ellenőrzött forrásként érhető el.</p><div class="flex" style="gap:.5rem;flex-wrap:wrap"><a class="btn btn-soft" href="#/hagymas">🗺️ Útvonalhálózat megnyitása</a><a class="btn btn-ghost" href="#/felfedezes">Ellenőrzött katalógus</a></div></section><section class="card v127-known"><h2>Valós katalógushelyek</h2><p class="small muted">Ezek a helyek a meglévő, forrásolt katalógusból érkeznek. Kattints egy helyre, majd válassz másik pontot.</p><div class="flex" style="gap:.45rem;flex-wrap:wrap">'+(knownPlaceHtml()||'<span class="small muted">Nincs koordinátával rendelkező katalógushely.</span>')+'</div></section><div id="v127-result"></div></div>'+footer(); };
VIEWS.planner.after=function(root){bindMapClicks(root);root.addEventListener("input",function(e){if(e.target.matches("#v127-start,#v127-end"))clearPoint(e.target);});root.addEventListener("click",function(e){var b=e.target.closest&&e.target.closest("[data-v127-search],[data-v127-gps],[data-v127-place],[data-v127-known-place]");if(!b)return;if(b.dataset.v127Search){search(root,b.dataset.v127Search);return;}if(b.dataset.v127Gps){gpsPoint(root,b.dataset.v127Gps);return;}if(b.dataset.v127KnownPlace){var p={lat:+b.dataset.lat,lng:+b.dataset.lng,label:b.dataset.label||"Katalógushely"};var active=root.querySelector(".v127-targets .on");setInputPoint(root,active&&active.dataset.v127Target==="end"?"#v127-end":"#v127-start",p);toast("A forrásolt katalógushely bekerült a pontba.","📍");return;}if(b.dataset.v127Place){var box=root.querySelector(b.dataset.v127Place==="start"?"#v127-start-results":"#v127-end-results"),rows=box&&box.__v127Rows||[],p=rows[+b.dataset.v127Index];if(p){setInputPoint(root,b.dataset.v127Place,p);box.innerHTML="";}return;}});var plan=root.querySelector("#v127-plan");if(plan)plan.onclick=function(){run(root);};};
window.V127Routing={version:"127",source:ORS_SOURCE,cache:cache,plan:routeRequest,routeToTrack:geometryToTrack};
})();
